---
- name: Search user
  set_fact:
    selected_user: >
      {{
      users
      | selectattr('username', 'defined')
      | selectattr('username', 'eq', item.user)
      | first
      }}

- name: Create storage
  file:
    path: "{{storage_volume}}/{{item.path}}"
    state: directory
    owner: "{{selected_user.uid}}"
    group: "{{selected_user.uid}}"
    mode: 0750
