---
- name: Create config directory structure
  file:
    path: "{{ config_volume }}/etc"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Check if passwd db exists
  stat:
    path: "{{ config_volume }}/etc/passwd"
  register: passwd_file

- name: Create passwd db
  file:
    path: "{{ config_volume }}/etc/passwd"
    state: touch
    owner: root
    group: root
    mode: 0644
  when: not passwd_file.stat.exists

- name: Check if shadow db exists
  stat:
    path: "{{ config_volume }}/etc/shadow"
  register: shadow_file

- name: Create shadow db
  file:
    path: "{{ config_volume }}/etc/shadow"
    state: touch
    owner: root
    group: root
    mode: 0640
  when: not shadow_file.stat.exists

- name: Check if group db exists
  stat:
    path: "{{ config_volume }}/etc/group"
  register: group_file

- name: Create group db
  file:
    path: "{{ config_volume }}/etc/group"
    state: touch
    owner: root
    group: root
    mode: 0640
  when: not group_file.stat.exists

- name: Create etc/netatalk directory
  file:
    path: "{{ config_volume }}/etc/netatalk"
    state: directory
    owner: root
    group: root
    mode: 0755
