---
- name: Search user
  set_fact:
    selected_user: >
      {{
      timemachine_users
      | selectattr('username', 'defined')
      | selectattr('username', 'eq', item.user)
      | first
      }}

- name: Create storage
  file:
    path: "{{ timemachine_storage_volume }}/{{ item.path }}"
    state: directory
    owner: "{{ selected_user.uid }}"
    group: "{{ selected_user.uid }}"
    mode: 0750
