---
- name: Create docker working directory
  file:
    path: "{{ timemachine_working_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create dockerimage directory
  file:
    path: "{{ timemachine_dockerfile_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy docker entrypoint
  copy:
    src: files/entrypoint.sh
    dest: "{{ timemachine_dockerfile_path }}/entrypoint.sh"
    owner: root
    group: root
    mode: '0755'
  register: docker_entrypoint

- name: Copy add-user script
  copy:
    src: files/add-user.sh
    dest: "{{ timemachine_dockerfile_path }}/add-user.sh"
    owner: root
    group: root
    mode: '0755'
  register: docker_add_user_script

- name: Copy update-user-password script
  copy:
    src: files/update-user-password.sh
    dest: "{{ timemachine_dockerfile_path }}/update-user-password.sh"
    owner: root
    group: root
    mode: '0755'
  register: docker_update_user_password_script

- name: Template dockerfile
  template:
    src: Dockerfile.j2
    dest: "{{ timemachine_dockerfile_path }}/Dockerfile"
    owner: root
    group: root
    mode: 0644
  register: dockerfile

- name: Build dockerimage
  docker_image:
    build:
      path: "{{ timemachine_dockerfile_path }}"
      pull: false
    name: "{{ timemachine_image_name }}"
    tag: "{{ timemachine_netatalk_version }}"
    source: build
    state: present
    force_source: "{{
      dockerfile.changed
      or docker_entrypoint.changed
      or docker_add_user_script.changed
      or docker_update_user_password_script.changed
      or timemachine_force_build
      }}"
  notify: Restart timemachine service
