---
- name: Create docker working directory
  file:
    path: "{{ timemachine_working_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create dockerimage directory
  file:
    path: "{{ timemachine_dockerfile_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy docker entrypoint
  copy:
    src: files/entrypoint.sh
    dest: "{{ timemachine_dockerfile_path }}/entrypoint.sh"
    owner: root
    group: root
    mode: '0755'
  notify: Restart timemachine service

- name: Copy add-user script
  copy:
    src: files/add-user.sh
    dest: "{{ timemachine_dockerfile_path }}/add-user.sh"
    owner: root
    group: root
    mode: '0755'
  notify: Restart timemachine service

- name: Copy update-user-password script
  copy:
    src: files/update-user-password.sh
    dest: "{{ timemachine_dockerfile_path }}/update-user-password.sh"
    owner: root
    group: root
    mode: '0755'
  notify: Restart timemachine service

- name: Template dockerfile
  template:
    src: Dockerfile.j2
    dest: "{{ timemachine_dockerfile_path }}/Dockerfile"
    owner: root
    group: root
    mode: 0644
  notify: Restart timemachine service
