---
- name: Create docker working directory
  file:
    path: "{{working_directory}}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create dockerimage directory
  file:
    path: "{{dockerfile_path}}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy docker entrypoint
  copy:
    src: files/entrypoint.sh
    dest: "{{dockerfile_path}}/entrypoint.sh"
    owner: root
    group: root
    mode: '0755'
  register: docker_entrypoint

- name: Copy add-user script
  copy:
    src: files/add-timemachine-user.sh
    dest: "{{dockerfile_path}}/add-timemachine-user.sh"
    owner: root
    group: root
    mode: '0755'
  register: docker_add_user_script

- name: Template dockerfile
  template:
    src: Dockerfile.j2
    dest: "{{dockerfile_path}}/Dockerfile"
    owner: root
    group: root
    mode: 0644
  register: dockerfile

- name: Build dockerimage
  docker_image:
    build:
      path: "{{dockerfile_path}}"
      pull: no
    name: "{{image_name}}"
    tag: "{{netatalk_version}}"
    source: build
    state: present
    force_source: "{{
      dockerfile.changed
      or docker_entrypoint.changed
      or docker_add_user_script.changed
      or force_build
      }}"
  register: dockerimage
