---
- name: Create config directory
  file:
    path: "{{config_volume}}"
    state: directory
    owner: root
    group: root
    mode: 0755

- include: create-initial-netatalk-config.yml

- name: Create storage directories
  file:
    path: "{{storage_volume}}"
    state: directory
    owner: root
    group: root
    mode: 0777
