---
- name: Search storage
  set_fact:
    selected_storage: >
      {{
      storages
      | selectattr('user', 'defined')
      | selectattr('user', 'eq', item.username)
      | first
      }}

- name: Prepare user
  set_fact:
    user_to_create:
      uid: "{{ item.uid }}"
      username: "{{ item.username }}"
      password: "{{ item.password }}"
      storage: "{{ selected_storage }}"

- name: Determine if timemachine has to be created
  shell: |
    set -o pipefail
    cat {{ config_volume }}/etc/passwd \
    | grep {{ user_to_create.username }}:x:{{ user_to_create.uid }}
  args:
    executable: /bin/bash
  register: user_exists
  changed_when: user_exists.stdout | length < 1
    and not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
  failed_when: false
  notify: Create timemachine user

# I need this task cause I don't know another way to notify
# a handler with a parameter or variable
- name: Users for creation
  set_fact:
    users_for_creation: "{{ users_for_creation + [user_to_create] }}"
  when: user_exists.changed  # noqa 503
