---
- name: create config directory
  file:
    path: "{{config_volume}}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: not(
    (config_volume is undefined)
    or
    (config_volume is none)
    or
    (config_volume | trim == '')
    )

- name: create data directory
  file:
    path: "{{data_volume}}"
    state: directory
    owner: root
    group: root
    mode: 0775
  when: not(
    (data_volume is undefined)
    or
    (data_volume is none)
    or
    (data_volume | trim == '')
    )

- name: create storage directories
  file:
    path: "{{storage_volume}}"
    state: directory
    owner: root
    group: root
    mode: 0777
  when: not(
    (storage_volume is undefined)
    or
    (storage_volume is none)
    or
    (storage_volume | trim == '')
    )

- name: create lock directories
  file:
    path: "{{lock_volume}}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: not(
    (lock_volume is undefined)
    or
    (lock_volume is none)
    or
    (lock_volume | trim == '')
    )
