---
- name: Create config directory
  file:
    path: "{{ timemachine_config_volume }}"
    state: directory
    owner: root
    group: root
    mode: 0750

- include: create-initial-netatalk-config.yml

- name: Create storage directories
  file:
    path: "{{ timemachine_storage_volume }}"
    state: directory
    owner: root
    group: root
    mode: 0755
