---
- include: check-parameters.yml

- include: create-docker-image.yml
- include: create-volumes.yml

- include: create-storage.yml
  with_items: "{{ storages }}"

- include: setup-netatalk-config.yml
- include: setup-systemd-service.yml

- include: create-users.yml

- name: Start systemd-managed docker containers
  meta: flush_handlers

- name: Enable/start timemachine service (if not started)
  service:
    name: "{{ service_name }}"
    enabled: true
    state: started
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )

- include: update-user-password.yml
  with_items: >
    {{
    users
    | selectattr('update_password', 'true')
    | list
    }}
