---
- include_tasks: create-docker-image.yml
- include_tasks: create-volumes.yml

- include_tasks: create-storage.yml
  with_items: "{{ timemachine_storages }}"

- include_tasks: setup-netatalk-config.yml
- include_tasks: setup-systemd-service.yml

- include_tasks: create-users.yml

- name: Start systemd-managed docker containers
  meta: flush_handlers

- name: Enable/start timemachine service (if not started)
  service:
    name: "{{ timemachine_service_name }}"
    enabled: true
    state: started
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )

- include_tasks: update-user-password.yml
  with_items: >
    {{
    timemachine_users
    | selectattr('update_password', 'true')
    | list
    }}
