---
- include: check-parameters.yml

- include: create-docker-image.yml
- include: create-volumes.yml

- include: create-storage.yml
  with_items: "{{storages}}"

- include: setup-netatalk-config.yml
- include: setup-systemd-service.yml

- include: create-user.yml
  with_items: "{{users}}"
