---
- name: Create systemd unit file
  template:
    src: timemachine.systemd.j2
    dest: "/etc/systemd/system/{{service_name}}.service"
    owner: root
    group: root
    mode: 0644
  register: systemd_service

- name: Reload systemd
  command: systemctl daemon-reload
  when: systemd_service.changed

- name: Restart service
  service:
    name: "{{service_name}}"
    state: restarted
    enabled: yes
  when: >
    dockerimage.changed
    or systemd_service.changed
    or timemachine_config.changed

- name: Start service (if not started already)
  service:
    name: "{{service_name}}"
    state: started
