---
- name: Create systemd unit file
  template:
    src: timemachine.systemd.j2
    dest: "/etc/systemd/system/{{ timemachine_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart timemachine service
