---
- name: Create systemd unit file
  template:
    src: timemachine.systemd.j2
    dest: "/etc/systemd/system/{{ service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload systemd
    - Restart timemachine service

- name: Enable service
  service:
    name: "{{ service_name }}"
    enabled: true
  register: timemachine_service
  changed_when: timemachine_service.status.SubState != 'running'
  notify: Start timemachine service
