---
- name: Update user password
  shell: |
    /usr/bin/docker exec {{container_name}} /update-user-password.sh "{{item.username}}" '{{item.password}}'
  register: user_password_updated
  changed_when: user_password_updated.stdout | length > 0
