# disk = './.vagrant/tmp/secondDisk.vdi'

Vagrant.configure("2") do |config|
#   config.vm.box = "ubuntu/xenial64"
  config.vm.box = "ubuntu/bionic64"
#   config.vm.box = "ubuntu/focal64"

  config.vm.network "private_network", ip: "192.168.33.29"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ansible_timemachine"
    vb.memory = 1024
    vb.cpus = 1
  end
end
