---
- name: Reload systemd
  systemd:
    daemon_reload: true
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )

- name: Start timemachine service
  service:
    name: "{{ service_name }}"
    state: started
  register: timemachine_start

- name: Restart timemachine service
  service:
    name: "{{ service_name }}"
    state: restarted
  register: timemachine_service_restart
  when: not (
    timemachine_start is defined
    and timemachine_start.changed
    )
    and not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )

- name: Create timemachine user
  shell: |
    /usr/bin/docker exec {{ container_name }} \
      /add-user.sh {{ item.uid }} \
                   "{{ item.username }}" \
                   '{{ item.password }}' \
                   "/media/time_machine/{{ item.storage }}"
  register: created_user
  changed_when: created_user.stdout | length > 0
  with_items: "{{ users_for_creation }}"
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
