---
- name: Restart timemachine service
  systemd:
    name: "{{ timemachine_service_name }}"
    state: restarted
    daemon_reload: true
  register: timemachine_service_restart
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )

- name: Create timemachine user
  shell: |
    /usr/bin/docker exec {{ timemachine_container_name }} \
      /add-user.sh {{ item.uid }} \
                   "{{ item.username }}" \
                   '{{ item.password }}' \
                   "/media/time_machine/{{ item.storage }}"
  register: created_user
  changed_when: created_user.stdout | length > 0
  with_items: "{{ users_for_creation }}"
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
