---
- name: Prepare
  hosts: all
  become: true

  roles:
    - role: install-docker
      docker_storage_driver: overlay2
      docker_cleanup_enabled: false
      when: not (
        molecule_docker_environment is defined
        and molecule_docker_environment | bool
        )

  post_tasks:
    - name: Install netcat on Debian-based systems (to test open ports)
      package:
        name: netcat-traditional
        state: present
      when: ansible_os_family == 'Debian'
