---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: ansible-timemachine
      timemachine_alpine_version: '3.11'
      timemachine_netatalk_version: '3.1'
      timemachine_host_name: my-ansible-timemachine
      timemachine_mimic_model: RackMac
      timemachine_storage_volume: /srv/timemachine/storage
      timemachine_config_volume: /srv/timemachine/config
      timemachine_interface: 0.0.0.0
      timemachine_netatalk_port: 548
      timemachine_log_level: error
      timemachine_users:
        - username: user1
          password: user1pwd
          uid: 2001
        - username: user2
          password: psw2
          uid: 2002
      timemachine_storages:
        - name: Time Machine user1
          path: storage1
          user: user1
          size_limit: 256000
        - name: Time Machine user2
          path: storage2
          user: user2
          size_limit: 64000
