---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: ansible-timemachine
      alpine_version: '3.11'
      netatalk_version: '3.1'
      host_name: my-ansible-timemachine
      mimic_model: RackMac
      server_name: My Time Machine
      storage_volume: /srv/timemachine/storage
      config_volume: /srv/timemachine/config
      interface: 0.0.0.0
      netatalk_port: 548
      log_level: error
      users:
        - username: user1
          password: user1pwd
          uid: 2001
        - username: user2
          password: psw2
          uid: 2002
      storages:
        - name: Time Machine user1
          path: storage1
          user: user1
          size_limit: 256000
        - name: Time Machine user2
          path: storage2
          user: user2
          size_limit: 64000
