{% if timemachine_alpine_version is not defined or timemachine_alpine_version == 'latest' %}
FROM alpine
{% else %}
FROM alpine:{{timemachine_alpine_version}}
{% endif %}

MAINTAINER "Boris Skert <boris.skert@gmail.com>"

RUN apk --no-cache --no-progress upgrade && \
    apk --no-cache --no-progress add \
        bash \
        tini \
{% if timemachine_netatalk_version is not defined or timemachine_netatalk_version == 'latest' %}
        netatalk
{% else %}
        netatalk~={{timemachine_netatalk_version}}
{% endif %}

COPY ./entrypoint.sh /entrypoint.sh
COPY ./add-user.sh /add-user.sh
COPY ./update-user-password.sh /update-user-password.sh

VOLUME /media/time_machine
VOLUME /etc
VOLUME /var/netatalk
VOLUME /var/lock

EXPOSE 548

ENTRYPOINT ["/sbin/tini", "--", "/entrypoint.sh"]
