---
dependency:
  name: galaxy
  options:
    role-file: ./molecule/default/requirements.yml
    force: true

driver:
  name: vagrant
  provider:
    name: libvirt

platforms:
  - name: ansible-timemachine-noble
    box: cloud-image/ubuntu-24.04
  - name: ansible-timemachine-jammy
    box: cloud-image/ubuntu-22.04
  - name: ansible-timemachine-focal
    box: cloud-image/ubuntu-20.04
  - name: ansible-timemachine-bookworm
    box: cloud-image/debian-12
    groups:
      - debian
  - name: ansible-timemachine-bullseye
    box: cloud-image/debian-11
    groups:
      - debian

provisioner:
  name: ansible
  playbooks:
    prepare: ../default/prepare.yml
    converge: ../all-parameters/converge.yml
    verify: ../all-parameters/verify.yml
  inventory:
    group_vars:
      debian:
        ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible
